#!/bin/sh -e

GREEN="$(printf '\033[1;32m')"
YELLOW="$(printf '\033[1;33m')"
NC="$(printf '\033[0m')"

SYSTEM_TYPE="$(nix eval --impure --expr 'builtins.currentSystem' | tr -d '"')"
FLAKE_SYSTEM="darwinConfigurations.${SYSTEM_TYPE}.system"

export NIXPKGS_ALLOW_UNFREE=1

echo "${YELLOW}Starting build...${NC}"
nix --extra-experimental-features 'nix-command flakes' build ".#${FLAKE_SYSTEM}" "$@"

echo "${YELLOW}Cleaning up...${NC}"
unlink ./result

echo "${GREEN}Switch to new generation complete!${NC}"
