#!/usr/bin/env bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

username=${USER}
export SECRETS_DIR=/Users/${username}/.secrets

lint_keys() {
  if [[ -f "${SECRETS_DIR}/master.age.key" ]]; then
    echo -e "${GREEN}All keys are present in ${SECRETS_DIR}.${NC}"
  else
    echo -e "${RED}The age identity key is missing.${NC}"
    if [[ ! -f "${SECRETS_DIR}/master.age.key" ]]; then
      echo -e "${RED}Missing: master.age.key${NC}"
    fi
    echo -e "${GREEN}Run #copy-keys to copy the key from a USB drive, or #create-keys to create a new age identity key which you can then use to encrypt and decrypt new secrets.${NC}"
    exit 1
  fi
}

lint_keys
