#!/bin/sh -e

RED="$(printf '\033[1;31m')"
GREEN="$(printf '\033[1;32m')"
YELLOW="$(printf '\033[1;33m')"
NC="$(printf '\033[0m')"

SYSTEM=$(uname -m)
case "$SYSTEM" in
x86_64)
  SYSTEM="x86_64"
  ;;
aarch64)
  SYSTEM="aarch64"
  ;;
*)
  echo -e "${RED}Unsupported architecture: $SYSTEM${NC}"
  exit 1
  ;;
esac

if systemd-detect-virt --quiet; then
  HOST="vm"
else
  HOST="nixos"
fi

FLAKE_TARGET="$HOST-$SYSTEM"
echo -e "${YELLOW}Building configuration for $FLAKE_TARGET...${NC}"

sudo nixos-rebuild switch --flake ".#$FLAKE_TARGET" "$@"

echo -e "${GREEN}Switch to new generation complete!${NC}"
